leftnav:
- identifier: 94cd727e-2d9b-4f3a-b914-fd4d2edba7c2
  name: Course Information
  url: /pages/course-information
  weight: 10
- identifier: 745d7c97-71de-46d8-81dc-859108b06bd8
  name: Introduction
  url: /pages/introduction
  weight: 20
- identifier: 07d0c681-2cf0-4241-b8a9-b1865b183e42
  name: What is Engineering?
  url: /pages/what-is-engineering
  weight: 30
- identifier: 06021acd-609a-416e-8442-4ee43941eded
  name: What are Common STEM Fields?
  url: /pages/engineering-fields
  weight: 40
- identifier: 9339e88d-fbfa-492e-82c4-080fdf00664d
  name: Core STEM Fields
  parent: 07d0c681-2cf0-4241-b8a9-b1865b183e42
  url: /pages/core-stem-fields
  weight: 10
- identifier: 1c082150-35bb-4236-af04-c67f3976fd42
  name: Bioengineering
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/bioengineering
  weight: 10
- identifier: 53b4f731-d3c7-4f34-884f-b1194d6f6ad0
  name: Civil Engineering
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/civil-engineering
  weight: 20
- identifier: 8debd02e-6b15-4fca-8da4-a790605c77e9
  name: Chemical Engineering
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/chemical-engineering
  weight: 30
- identifier: 37609b1f-ecd4-4a38-80ff-9f096a385830
  name: Computer Science
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/computer-science
  weight: 40
- identifier: 139d8a89-a0b2-4764-8521-182d2361d283
  name: Data Science
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/data-science
  weight: 50
- identifier: d4a2477d-d6ef-4a17-abb2-c4d4e18e45b8
  name: Electrical / Electronic
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/electrical-electronic-engineering
  weight: 60
- identifier: f80e2b40-8e12-4587-a990-e4fb27e443e9
  name: Environmental Engineering
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/environmental-engineering
  weight: 70
- identifier: c9c42ba7-62f4-4412-ab3b-2b9abeb6fbe6
  name: Mechanical Engineering
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/mechanical-engineering
  weight: 80
- identifier: 6e3ee185-f87f-46da-93b4-d213eec53d4d
  name: Nuclear Engineering
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/nuclear-engineering
  weight: 90
- identifier: d8b3e398-0180-4d5f-b9e9-b4cd00e89ac1
  name: Software Engineering
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/software-engineering
  weight: 100
- identifier: 7c445ba5-1b4c-4962-a54d-e74fc4db0058
  name: Community-Focused Engineering Societies
  parent: 06021acd-609a-416e-8442-4ee43941eded
  url: /pages/community-focused-engineering-societies
  weight: 110
